<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Prdb.Viewer.Core\Prdb.Viewer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
    <PackageReference Include="Prdb.Sdk" />
    <PackageReference Include="Prdb.Hashing" />
  </ItemGroup>

</Project>
