/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessStateResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BootstrapRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BootstrapResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignInRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignInResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/registration-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegistrationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegistrationRequestResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecoverRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecoverResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignedInAccountResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts/{accountId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountActionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts/{accountId}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountActionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts/{accountId}/recovery-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecoveryCodeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstallationConfigurationSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configuration/prdb-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PrdbCredentialRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrdbConnectionUpdateResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configuration/prdb-connection/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrdbConnectionUpdateResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configuration/library-directory-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryDirectoryCandidatesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configuration/library-directories/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LibraryDirectoryStageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryDirectoryStageResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configuration/library-directories/stages/{stageId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    stageId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryDirectoryActivationResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessStateResponse: {
            claimed: boolean;
            signedIn: boolean;
        };
        AccountActionResponse: {
            verdict: components["schemas"]["AccountActionVerdict"];
        };
        /** @enum {unknown} */
        AccountActionVerdict: "Completed" | "NotFound" | "InvalidState" | "LastAdministrator";
        /** @enum {unknown} */
        AccountAuthority: "User" | "Administrator";
        /** @enum {unknown} */
        AccountState: "PendingApproval" | "Approved" | "Disabled";
        AccountSummary: {
            /** Format: uuid */
            id: string;
            username: string;
            email: null | string;
            authority: components["schemas"]["AccountAuthority"];
            state: components["schemas"]["AccountState"];
            /** Format: date-time */
            registeredAt: string;
        };
        /** @enum {unknown} */
        BootstrapClaimVerdict: "Created" | "InvalidInput" | "InvalidAuthorization" | "AlreadyClaimed";
        BootstrapRequest: {
            authorization: null | string;
            username: null | string;
            password: null | string;
            email: null | string;
        };
        BootstrapResponse: {
            verdict: components["schemas"]["BootstrapClaimVerdict"];
            account: null | components["schemas"]["SignedInAccountResponse"];
        };
        HealthResponse: {
            status: string;
        };
        /** @enum {unknown} */
        InstallationConfigurationStatus: "Unclaimed" | "ConfigurationRequired" | "ConfigurationPending" | "AttentionRequired" | "Configured";
        InstallationConfigurationSummary: {
            status: components["schemas"]["InstallationConfigurationStatus"];
            prdbConnectionStatus: components["schemas"]["PrdbConnectionStatus"];
            hasPrdbCredential: boolean;
            credentialReplacementPending: boolean;
            /** Format: date-time */
            lastConnectionAttemptAt: null | string;
            /** Format: date-time */
            lastConnectionVerifiedAt: null | string;
            lastConnectionIssue: null | components["schemas"]["PrdbConnectionIssue"];
            libraryMountRoot: string;
            libraryDirectories: components["schemas"]["LibraryDirectorySummary"][];
        };
        LibraryDirectoryActivationResult: {
            verdict: components["schemas"]["LibraryDirectoryActivationVerdict"];
            directory?: null | components["schemas"]["LibraryDirectorySummary"];
        };
        /** @enum {unknown} */
        LibraryDirectoryActivationVerdict: "Activated" | "NotFound" | "Expired" | "NoLongerValid" | "AlreadyConfigured";
        LibraryDirectoryCandidatesResponse: {
            containerPaths: string[];
        };
        /** @enum {unknown} */
        LibraryDirectoryHealth: "Healthy" | "PartiallyUnreachable" | "Unreachable";
        LibraryDirectoryStageRequest: {
            name: null | string;
            containerPath: null | string;
        };
        LibraryDirectoryStageResult: {
            verdict: components["schemas"]["LibraryDirectoryStageVerdict"];
            /** Format: uuid */
            stageId?: null | string;
            name?: null | string;
            containerPath?: null | string;
            /** Format: date-time */
            expiresAt?: null | string;
        };
        /** @enum {unknown} */
        LibraryDirectoryStageVerdict: "Staged" | "InvalidInput" | "OutsideMountArea" | "Missing" | "Unreadable" | "AlreadyConfigured";
        /** @enum {unknown} */
        LibraryDirectoryState: "Active" | "Removed";
        LibraryDirectorySummary: {
            /** Format: uuid */
            id: string;
            name: string;
            containerPath: string;
            state: components["schemas"]["LibraryDirectoryState"];
            health: components["schemas"]["LibraryDirectoryHealth"];
            /** Format: int32 */
            configurationGeneration: number | string;
            /** Format: date-time */
            activatedAt: string;
            initialProcessingStarted: boolean;
        };
        /** @enum {unknown} */
        PrdbConnectionIssue: "ExternalAuthority" | "ExternalAvailability" | "ReplacementRejected" | null;
        /** @enum {unknown} */
        PrdbConnectionStatus: "Missing" | "VerificationPending" | "Verified" | "Rejected" | "Degraded";
        PrdbConnectionUpdateResult: {
            verdict: components["schemas"]["PrdbConnectionUpdateVerdict"];
        };
        /** @enum {unknown} */
        PrdbConnectionUpdateVerdict: "Verified" | "Rejected" | "VerificationPending" | "Missing" | "InvalidInput" | "Superseded";
        PrdbCredentialRequest: {
            credential: null | string;
        };
        RecoverRequest: {
            username: null | string;
            recoveryCode: null | string;
            newPassword: null | string;
        };
        RecoverResponse: {
            verdict: components["schemas"]["RecoveryVerdict"];
        };
        RecoveryCodeResponse: {
            verdict: components["schemas"]["AccountActionVerdict"];
            recoveryCode: null | string;
            /** Format: date-time */
            expiresAt: null | string;
        };
        /** @enum {unknown} */
        RecoveryVerdict: "PasswordReplaced" | "InvalidInput" | "InvalidCode";
        RegistrationRequest: {
            username: null | string;
            password: null | string;
            email: null | string;
        };
        RegistrationRequestResponse: {
            verdict: components["schemas"]["RegistrationRequestVerdict"];
        };
        /** @enum {unknown} */
        RegistrationRequestVerdict: "Submitted" | "InvalidInput" | "InstallationUnclaimed";
        SignedInAccountResponse: {
            /** Format: uuid */
            id: string;
            username: string;
            email: null | string;
            authority: components["schemas"]["AccountAuthority"];
            csrfToken: string;
        };
        SignInRequest: {
            username: null | string;
            password: null | string;
        };
        SignInResponse: {
            verdict: components["schemas"]["SignInVerdict"];
            account: null | components["schemas"]["SignedInAccountResponse"];
        };
        /** @enum {unknown} */
        SignInVerdict: "SignedIn" | "InvalidCredentials" | "ApprovalPending" | "Disabled";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
