/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/previews/{previewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    previewId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/proposals/{artworkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    artworkId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/videos/{deliveryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deliveryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/actors/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    imageId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessStateResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BootstrapRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BootstrapResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignInRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignInResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/registration-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegistrationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegistrationRequestResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecoverRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecoverResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignedInAccountResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts/{accountId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountActionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts/{accountId}/reinstate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountActionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts/{accountId}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountActionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts/{accountId}/recovery-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecoveryCodeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstallationConfigurationSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configuration/prdb-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PrdbCredentialRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrdbConnectionUpdateResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configuration/prdb-connection/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrdbConnectionUpdateResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configuration/library-directory-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryDirectoryCandidatesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configuration/library-directories/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LibraryDirectoryStageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryDirectoryStageResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configuration/library-directories/stages/{stageId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    stageId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryDirectoryActivationResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configuration/library-directories/{libraryDirectoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    libraryDirectoryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryDirectoryRemovalResult"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/background-work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackgroundWorkStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/background-work/issues/{workIssueId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workIssueId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkIssueAffectedItem"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/background-work/issues/{workIssueId}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workIssueId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkIssueActionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackgroundWorkActionResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/background-work/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BackgroundWorkPauseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackgroundWorkPauseResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/background-work/{workId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackgroundWorkActionResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/background-work/library-directories/{libraryDirectoryId}/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    libraryDirectoryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QueueLibraryScanResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/identification/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdentificationQueueItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/identification/videos/{videoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/identification/videos/{videoId}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IdentificationDecisionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdentificationDecisionResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    query?: string;
                    sort?: components["schemas"]["LibrarySortOrder"];
                    sites?: string;
                    actors?: string;
                    unknownSite?: boolean;
                    work?: string;
                    review?: string;
                    playability?: string;
                    availability?: string;
                    quality?: string;
                    playState?: string;
                    shelf?: string;
                    skip?: number | string;
                    take?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/videos/{videoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VideoDetail"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    query?: string;
                    sites?: string;
                    actors?: string;
                    unknownSite?: boolean;
                    work?: string;
                    review?: string;
                    playability?: string;
                    availability?: string;
                    quality?: string;
                    playState?: string;
                    shelf?: string;
                    siteSearch?: string;
                    actorSearch?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryFacets"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/preferences/include-not-ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IncludeNotReadyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryPreferencesSummary"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/actors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    query?: string;
                    sort?: components["schemas"]["ActorSortOrder"];
                    skip?: number | string;
                    take?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActorIndexPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/actors/{actorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    actorId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActorDetail"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/playback-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnassessedPlaybackProfile"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/playback-assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientPlaybackAssessmentsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientPlaybackAssessmentsResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/playback-outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ObservedPlaybackOutcomeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ObservedPlaybackOutcomeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/videos/{videoId}/playback-outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ObservedPlaybackOutcomeResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/videos/{videoId}/playback-attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlaybackAttemptRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlaybackAttemptResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/playback-attempts/{playbackAttemptId}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    playbackAttemptId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlaybackReportRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlaybackReportResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/playback-attempts/{playbackAttemptId}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    playbackAttemptId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EndPlaybackAttemptResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/videos/{videoId}/favourite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonalStateMutationResult"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonalStateMutationResult"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/videos/{videoId}/watch-later": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonalStateMutationResult"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonalStateMutationResult"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/videos/{videoId}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PersonalRatingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonalStateMutationResult"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonalStateMutationResult"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/videos/{videoId}/continue-watching/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonalStateMutationResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessStateResponse: {
            claimed: boolean;
            signedIn: boolean;
        };
        AccountActionResponse: {
            verdict: components["schemas"]["AccountActionVerdict"];
        };
        /** @enum {unknown} */
        AccountActionVerdict: "Completed" | "NotFound" | "InvalidState" | "LastAdministrator";
        /** @enum {unknown} */
        AccountAuthority: "User" | "Administrator";
        /** @enum {unknown} */
        AccountState: "PendingApproval" | "Approved" | "Disabled";
        AccountSummary: {
            /** Format: uuid */
            id: string;
            username: string;
            email: null | string;
            authority: components["schemas"]["AccountAuthority"];
            state: components["schemas"]["AccountState"];
            /** Format: date-time */
            registeredAt: string;
        };
        ActorCreditView: {
            name: string;
            actorId: null | string;
        };
        ActorDetail: {
            actorId: string;
            name: string;
            profileState: components["schemas"]["ActorProfileState"];
            /** Format: date-time */
            profileFetchedAt: null | string;
            genderLabel: null | string;
            /** Format: date-time */
            birthday: null | string;
            birthdayPrecisionLabel: null | string;
            /** Format: date-time */
            deathday: null | string;
            birthplace: null | string;
            haircolourLabel: null | string;
            eyecolourLabel: null | string;
            breastTypeLabel: null | string;
            /** Format: int32 */
            heightCentimetres: null | number | string;
            braSizeLabel: null | string;
            /** Format: int32 */
            waistCentimetres: null | number | string;
            /** Format: int32 */
            hipCentimetres: null | number | string;
            nationalityLabel: null | string;
            ethnicityLabel: null | string;
            /** Format: int32 */
            careerStart: null | number | string;
            /** Format: int32 */
            careerEnd: null | number | string;
            tattoos: null | string;
            piercings: null | string;
            aliases: string[];
            links: components["schemas"]["ActorLinkView"][];
            bios: string[];
            images: components["schemas"]["ActorImageView"][];
            /** Format: int32 */
            offeredImageCount: number | string;
            videos: components["schemas"]["VideoSummary"][];
            /** Format: int32 */
            totalVideos: number | string;
            creditedNames: string[];
        };
        ActorImageView: {
            url: string;
            kindLabel: null | string;
        };
        ActorIndexPage: {
            actors: components["schemas"]["ActorSummary"][];
            /** Format: int32 */
            totalMatches: number | string;
            hasMore: boolean;
            /** Format: int32 */
            awaitingProfiles: number | string;
        };
        ActorLinkView: {
            url: string;
            siteLabel: null | string;
        };
        /** @enum {unknown} */
        ActorProfileState: "Pending" | "Retained" | "Unavailable";
        /** @enum {unknown} */
        ActorSortOrder: "Name" | "MostHere";
        ActorSummary: {
            actorId: string;
            name: string;
            portraitUrl: null | string;
            genderLabel: null | string;
            /** Format: int32 */
            videoCount: number | string;
            profileState: components["schemas"]["ActorProfileState"];
        };
        BackgroundWorkActionResult: {
            verdict: components["schemas"]["BackgroundWorkActionVerdict"];
            issue?: null | components["schemas"]["WorkIssueSummary"];
        };
        /** @enum {unknown} */
        BackgroundWorkActionVerdict: "Accepted" | "NotFound" | "AlreadySettled" | "Stale" | "NotApplicable";
        /** @enum {unknown} */
        BackgroundWorkCategory: "LibraryScan" | "TechnicalInspection" | "Hashing" | "PreviewGeneration" | "Identification" | "SiteRecognition" | "Enrichment";
        BackgroundWorkPauseRequest: {
            paused: boolean;
        };
        BackgroundWorkPauseResult: {
            paused: boolean;
            /** Format: date-time */
            pausedAt: null | string;
        };
        /** @enum {unknown} */
        BackgroundWorkState: "Queued" | "Running" | "Waiting" | "Paused" | "Completed" | "CompletedWithIssues" | "Cancelled";
        BackgroundWorkStatus: {
            work: components["schemas"]["BackgroundWorkSummary"][];
            issues: components["schemas"]["WorkIssueSummary"][];
            recentlyResolvedIssues: components["schemas"]["WorkIssueSummary"][];
            operationalAttention: boolean;
            /** Format: int32 */
            operationalAttentionCount: number | string;
            paused: boolean;
            /** Format: date-time */
            pausedAt: null | string;
        };
        BackgroundWorkSummary: {
            /** Format: uuid */
            id: string;
            category: components["schemas"]["BackgroundWorkCategory"];
            state: components["schemas"]["BackgroundWorkState"];
            trigger: components["schemas"]["BackgroundWorkTrigger"];
            phase: string;
            /** Format: uuid */
            libraryDirectoryId: string;
            libraryDirectoryName: string;
            /** Format: int32 */
            discoveredCandidateCount: number | string;
            /** Format: int32 */
            completedItemCount: number | string;
            /** Format: int32 */
            issueCount: number | string;
            /** Format: int32 */
            completedPercent: null | number | string;
            waitingReason: null | string;
            /** Format: date-time */
            nextAttemptAt: null | string;
            cancellationRequested: boolean;
            cancellable: boolean;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            startedAt: null | string;
            /** Format: date-time */
            lastActivityAt: null | string;
            /** Format: date-time */
            finishedAt: null | string;
        };
        /** @enum {unknown} */
        BackgroundWorkTrigger: "Activation" | "Administrator" | "FollowUpWork" | "IssueRetry" | "Periodic";
        /** @enum {unknown} */
        BootstrapClaimVerdict: "Created" | "InvalidInput" | "InvalidAuthorization" | "AlreadyClaimed";
        BootstrapRequest: {
            authorization: null | string;
            username: null | string;
            password: null | string;
            email: null | string;
        };
        BootstrapResponse: {
            verdict: components["schemas"]["BootstrapClaimVerdict"];
            account: null | components["schemas"]["SignedInAccountResponse"];
        };
        ClientPlaybackAssessmentReport: {
            profileKey: string;
            verdict: components["schemas"]["ClientPlaybackAssessmentVerdict"];
            smooth: null | boolean;
            powerEfficient: null | boolean;
            method: string;
        };
        ClientPlaybackAssessmentsRequest: {
            assessments: components["schemas"]["ClientPlaybackAssessmentReport"][];
        };
        ClientPlaybackAssessmentsResponse: {
            /** Format: int32 */
            recorded: number | string;
        };
        /** @enum {unknown} */
        ClientPlaybackAssessmentVerdict: "Indeterminate" | "Positive" | "Negative" | null;
        /** @enum {unknown} */
        ClientVideoPlayability: "ReadyForDirectPlay" | "CompatibilityUncertain" | "NotDirectlyPlayable";
        /** @enum {unknown} */
        DirectPlayClassification: "BaselineCandidate" | "ClientDependent" | "Unsupported" | "Undetermined";
        EndPlaybackAttemptResponse: {
            ended: boolean;
        };
        HealthResponse: {
            status: string;
        };
        /** @enum {unknown} */
        IdentificationCandidateStatus: "Pending" | "Rejected" | "Superseded";
        IdentificationCandidateView: {
            /** Format: uuid */
            id: string;
            dimension: components["schemas"]["IdentificationDimension"];
            status: components["schemas"]["IdentificationCandidateStatus"];
            targetTitle: string;
            targetUrl: null | string;
            evidenceClass: components["schemas"]["IdentificationEvidenceClass"];
            reason: components["schemas"]["IdentificationReviewReason"];
            source: components["schemas"]["IdentificationSource"];
            evidenceSummary: string;
            /** Format: uuid */
            supportingVideoFileId: null | string;
            proposal: null | components["schemas"]["IdentificationProposalView"];
            decisions: components["schemas"]["IdentificationDecisionOutlook"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            resolvedAt: null | string;
        };
        IdentificationCase: {
            /** Format: uuid */
            videoId: string;
            /** Format: int32 */
            caseVersion: number | string;
            displayLabel: string;
            previewUrl: null | string;
            identification: components["schemas"]["IdentificationSummary"];
            openCandidates: components["schemas"]["IdentificationCandidateView"][];
            candidateHistory: components["schemas"]["IdentificationCandidateView"][];
            videoFiles: components["schemas"]["IdentificationCaseFile"][];
            decisions: components["schemas"]["IdentificationDecisionView"][];
            unavailableSiteActions: components["schemas"]["IdentificationDecisionAction"][];
            explanation: string;
        };
        IdentificationCaseFile: {
            /** Format: uuid */
            id: string;
            relativePath: string;
            availability: components["schemas"]["VideoFileAvailability"];
            directPlayClassification: components["schemas"]["DirectPlayClassification"];
            containerFormat: string;
            videoCodec: string;
            audioCodec: null | string;
            /** Format: int64 */
            durationMilliseconds: number | string;
            osHashSummary: null | string;
            perceptualHashSummary: null | string;
            hashState: components["schemas"]["VideoFileHashState"];
        };
        IdentificationClaimView: {
            dimension: components["schemas"]["IdentificationDimension"];
            resolution: components["schemas"]["IdentificationResolution"];
            reviewStatus: components["schemas"]["IdentificationReviewStatus"];
            targetTitle: null | string;
            targetUrl: null | string;
            source: null | components["schemas"]["IdentificationSource"];
            evidenceClass: null | components["schemas"]["IdentificationEvidenceClass"];
            administrativeOverride: boolean;
            /** Format: date-time */
            establishedAt: null | string;
            /** Format: date-time */
            lastConfirmedAt: null | string;
        };
        IdentificationConsequence: {
            claimTransition: string;
            candidateTransition: string;
            /** Format: int32 */
            affectedVideoFileCount: number | string;
            resultingReviewStatus: components["schemas"]["IdentificationReviewStatus"];
            mergesAnotherVideo: boolean;
            mergeSummary: null | string;
            requiresNote: boolean;
        };
        /** @enum {unknown} */
        IdentificationDecisionAction: "AcceptCandidate" | "AssignDirectly" | "ReplaceClaim" | "RejectCandidate" | "RevokeClaim" | "SplitVideo";
        IdentificationDecisionOutlook: {
            action: components["schemas"]["IdentificationDecisionAction"];
            refusal: null | string;
            outcome: string;
        };
        IdentificationDecisionRequest: {
            action: components["schemas"]["IdentificationDecisionAction"];
            dimension: components["schemas"]["IdentificationDimension"];
            /** Format: int32 */
            caseVersion: number | string;
            confirm: boolean;
            /** Format: uuid */
            candidateId?: null | string;
            targetKey?: null | string;
            targetTitle?: null | string;
            targetUrl?: null | string;
            note?: null | string;
            separatedVideoFileIds?: null | string[];
            /** @default true */
            retainPersonalStateWithContinuing: boolean;
        };
        IdentificationDecisionResult: {
            verdict: components["schemas"]["IdentificationDecisionVerdict"];
            consequence?: null | components["schemas"]["IdentificationConsequence"];
            case?: null | components["schemas"]["IdentificationCase"];
        };
        /** @enum {unknown} */
        IdentificationDecisionVerdict: "Applied" | "Preview" | "Stale" | "NotFound" | "NoteRequired" | "InvalidTarget" | "ActionUnavailable";
        IdentificationDecisionView: {
            /** Format: uuid */
            id: string;
            dimension: components["schemas"]["IdentificationDimension"];
            action: components["schemas"]["IdentificationDecisionAction"];
            priorState: string;
            resultingState: string;
            mergedAnotherVideo: boolean;
            note: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {unknown} */
        IdentificationDimension: "WorkIdentification" | "SiteRecognition";
        /** @enum {unknown} */
        IdentificationEvidenceClass: "Insufficient" | "Suggestive" | "Conclusive";
        IdentificationProposalView: {
            title: string;
            siteTitle: null | string;
            siteUrl: null | string;
            actors: string[];
            artworkUrl: null | string;
            artworkState: components["schemas"]["ProposedWorkArtworkState"];
            /** Format: date-time */
            releaseDate: null | string;
            /** Format: int64 */
            durationMilliseconds: null | number | string;
            /** Format: date-time */
            fetchedAt: string;
        };
        IdentificationQueueItem: {
            /** Format: uuid */
            videoId: string;
            /** Format: int32 */
            caseVersion: number | string;
            displayLabel: string;
            previewUrl: null | string;
            dimension: components["schemas"]["IdentificationDimension"];
            currentResolution: components["schemas"]["IdentificationResolution"];
            currentTargetTitle: null | string;
            candidate: components["schemas"]["IdentificationCandidateView"];
            /** Format: int32 */
            affectedVideoFileCount: number | string;
            reason: string;
        };
        /** @enum {unknown} */
        IdentificationResolution: "Unknown" | "Established";
        /** @enum {unknown} */
        IdentificationReviewReason: "SuggestiveEvidence" | "ConflictingConclusiveEvidence" | "ConflictsWithAdministrativeOverride" | "RemoteIdentityChanged";
        /** @enum {unknown} */
        IdentificationReviewStatus: "Clear" | "ReviewNeeded";
        /** @enum {unknown} */
        IdentificationSource: "PrdbIdentification" | "LocalInference" | "AdministratorDecision";
        IdentificationSummary: {
            work: components["schemas"]["IdentificationClaimView"];
            site: components["schemas"]["IdentificationClaimView"];
            actors: components["schemas"]["ActorCreditView"][];
            /** Format: date-time */
            metadataFetchedAt: null | string;
        };
        IncludeNotReadyRequest: {
            included: boolean;
        };
        /** @enum {unknown} */
        InstallationConfigurationStatus: "Unclaimed" | "ConfigurationRequired" | "ConfigurationPending" | "AttentionRequired" | "Configured";
        InstallationConfigurationSummary: {
            status: components["schemas"]["InstallationConfigurationStatus"];
            prdbConnectionStatus: components["schemas"]["PrdbConnectionStatus"];
            hasPrdbCredential: boolean;
            credentialReplacementPending: boolean;
            /** Format: date-time */
            lastConnectionAttemptAt: null | string;
            /** Format: date-time */
            lastConnectionVerifiedAt: null | string;
            lastConnectionIssue: null | components["schemas"]["PrdbConnectionIssue"];
            /** Format: date-time */
            configuredAt: null | string;
            /** Format: date-time */
            firstPlayableVideoReachedAt: null | string;
            libraryMountRoot: string;
            libraryDirectories: components["schemas"]["LibraryDirectorySummary"][];
        };
        LibraryDirectoryActivationResult: {
            verdict: components["schemas"]["LibraryDirectoryActivationVerdict"];
            directory?: null | components["schemas"]["LibraryDirectorySummary"];
        };
        /** @enum {unknown} */
        LibraryDirectoryActivationVerdict: "Activated" | "NotFound" | "Expired" | "NoLongerValid" | "AlreadyConfigured";
        LibraryDirectoryCandidatesResponse: {
            containerPaths: string[];
        };
        /** @enum {unknown} */
        LibraryDirectoryHealth: "Healthy" | "PartiallyUnreachable" | "Unreachable";
        LibraryDirectoryRemovalResult: {
            verdict: components["schemas"]["LibraryDirectoryRemovalVerdict"];
            /**
             * Format: int32
             * @default 0
             */
            removedVideoFileCount: number | string;
            /**
             * Format: int32
             * @default 0
             */
            affectedVideoCount: number | string;
        };
        /** @enum {unknown} */
        LibraryDirectoryRemovalVerdict: "Removed" | "NotFound" | "AlreadyRemoved";
        LibraryDirectoryStageRequest: {
            name: null | string;
            containerPath: null | string;
        };
        LibraryDirectoryStageResult: {
            verdict: components["schemas"]["LibraryDirectoryStageVerdict"];
            /** Format: uuid */
            stageId?: null | string;
            name?: null | string;
            containerPath?: null | string;
            /** Format: date-time */
            expiresAt?: null | string;
        };
        /** @enum {unknown} */
        LibraryDirectoryStageVerdict: "Staged" | "InvalidName" | "InvalidPath" | "OutsideMountArea" | "Missing" | "Unreadable" | "AlreadyConfigured";
        /** @enum {unknown} */
        LibraryDirectoryState: "Active" | "Removed";
        LibraryDirectorySummary: {
            /** Format: uuid */
            id: string;
            name: string;
            containerPath: string;
            state: components["schemas"]["LibraryDirectoryState"];
            health: components["schemas"]["LibraryDirectoryHealth"];
            /** Format: int32 */
            configurationGeneration: number | string;
            /** Format: date-time */
            activatedAt: string;
            initialProcessingStarted: boolean;
            /** Format: int32 */
            availableVideoFileCount: number | string;
            /** Format: date-time */
            lastScanCompletedAt: null | string;
            /** Format: date-time */
            lastScanStartedAt: null | string;
            /** Format: int32 */
            lastScanCandidateCount: number | string;
            lastScanCoveredEverything: boolean;
            /** Format: date-time */
            nextScanDueAt: null | string;
        };
        LibraryFacets: {
            sites: components["schemas"]["LibraryFacetValue"][];
            actors: components["schemas"]["LibraryFacetValue"][];
            quality: components["schemas"]["LibraryQualityFacetValue"][];
            moreSites: boolean;
            moreActors: boolean;
        };
        LibraryFacetValue: {
            value: string;
            /** Format: int32 */
            count: number | string;
        };
        LibraryPage: {
            videos: components["schemas"]["VideoSummary"][];
            /** Format: int32 */
            totalMatches: number | string;
            /** Format: int32 */
            hiddenNotReadyForDirectPlay: number | string;
            /** Format: int32 */
            hiddenUnavailable: number | string;
            hasMore: boolean;
            includesNotReadyForDirectPlay: boolean;
        };
        LibraryPreferencesSummary: {
            includesNotReadyForDirectPlay: boolean;
        };
        LibraryQualityFacetValue: {
            value: components["schemas"]["VideoQualityBand"];
            /** Format: int32 */
            count: number | string;
        };
        /** @enum {unknown} */
        LibrarySortOrder: "Newest" | "TitleAscending" | "QualityDescending" | "LongestFirst" | "RecentlyPlayed" | "BestRated" | "ShelfOrder";
        /** @enum {unknown} */
        ObservedPlaybackOutcome: "Succeeded" | "Failed" | null;
        ObservedPlaybackOutcomeRequest: {
            /** Format: uuid */
            videoFileId: string;
            outcome: components["schemas"]["ObservedPlaybackOutcome"];
            failureCategory: null | components["schemas"]["PlaybackFailureCategory"];
        };
        ObservedPlaybackOutcomeResponse: {
            recorded: boolean;
        };
        /** @enum {unknown} */
        PersonalPlayState: "Unplayed" | "InProgress" | "Completed";
        PersonalRatingRequest: {
            /** Format: int32 */
            rating: null | number | string;
        };
        PersonalStateMutationResult: {
            verdict: components["schemas"]["PersonalStateMutationVerdict"];
            personalState: null | components["schemas"]["PersonalVideoStateSummary"];
        };
        /** @enum {unknown} */
        PersonalStateMutationVerdict: "Updated" | "VideoNotFound" | "InvalidRating";
        PersonalVideoStateSummary: {
            /** Format: int64 */
            playbackProgressMilliseconds: null | number | string;
            /** Format: int64 */
            accumulatedWatchDurationMilliseconds: number | string;
            /** Format: int32 */
            playCount: number | string;
            hasViewingCompletion: boolean;
            playState: components["schemas"]["PersonalPlayState"];
            continueWatching: boolean;
            favourite: boolean;
            watchLater: boolean;
            /** Format: int32 */
            personalRating: null | number | string;
        };
        PlaybackAttemptRequest: {
            /** Format: uuid */
            videoFileId: string;
        };
        PlaybackAttemptResult: {
            verdict: components["schemas"]["PlaybackAttemptVerdict"];
            /** Format: uuid */
            playbackAttemptId: null | string;
            /** Format: int64 */
            resumePositionMilliseconds: null | number | string;
        };
        /** @enum {unknown} */
        PlaybackAttemptVerdict: "Started" | "VideoNotFound" | "VideoFileUnavailable";
        /** @enum {unknown} */
        PlaybackFailureCategory: "Media" | "Availability" | "Delivery" | "Network" | null;
        PlaybackReportRequest: {
            /** Format: uuid */
            reportId: string;
            /** Format: int32 */
            sequence: number | string;
            /** Format: uuid */
            videoFileId: string;
            /** Format: int64 */
            positionMilliseconds: number | string;
            /** Format: int64 */
            activeWatchingMilliseconds: number | string;
            naturalEndConfirmed: boolean;
            endSession: boolean;
        };
        PlaybackReportResult: {
            verdict: components["schemas"]["PlaybackReportVerdict"];
            personalState: null | components["schemas"]["PersonalVideoStateSummary"];
        };
        /** @enum {unknown} */
        PlaybackReportVerdict: "Accepted" | "Duplicate" | "NotFound" | "AttemptEnded" | "InvalidReport";
        PlaybackVariantView: {
            /** Format: uuid */
            videoFileId: string;
            deliveryUrl: string;
            containerFormat: string;
            videoCodec: string;
            audioCodec: null | string;
            /** Format: int32 */
            width: null | number | string;
            /** Format: int32 */
            height: null | number | string;
            /** Format: double */
            frameRate: null | number | string;
            /** Format: int64 */
            bitrate: null | number | string;
            /** Format: int32 */
            audioChannels: null | number | string;
            /** Format: int32 */
            audioSampleRate: null | number | string;
            /** Format: int64 */
            audioBitrate: null | number | string;
            /** Format: int64 */
            size: number | string;
            /** Format: int64 */
            durationMilliseconds: number | string;
            qualityBand: components["schemas"]["VideoQualityBand"];
            directPlayClassification: components["schemas"]["DirectPlayClassification"];
            profileKey: string;
            preciseVideoContentType: null | string;
            preciseAudioContentType: null | string;
            basicContentType: null | string;
            assessment: null | components["schemas"]["ClientPlaybackAssessmentVerdict"];
            smooth: null | boolean;
            powerEfficient: null | boolean;
            outcome: null | components["schemas"]["ObservedPlaybackOutcome"];
            readyForDirectPlay: boolean;
            selectionReason: components["schemas"]["VariantSelectionReason"];
        };
        /** @enum {unknown} */
        PrdbConnectionIssue: "ExternalAuthority" | "ExternalAvailability" | "ReplacementRejected" | null;
        /** @enum {unknown} */
        PrdbConnectionStatus: "Missing" | "VerificationPending" | "Verified" | "Rejected" | "Degraded";
        PrdbConnectionUpdateResult: {
            verdict: components["schemas"]["PrdbConnectionUpdateVerdict"];
        };
        /** @enum {unknown} */
        PrdbConnectionUpdateVerdict: "Verified" | "Rejected" | "VerificationPending" | "Missing" | "InvalidInput" | "Superseded";
        PrdbCredentialRequest: {
            credential: null | string;
        };
        /** @enum {unknown} */
        ProposedWorkArtworkState: "None" | "Pending" | "Retained" | "Unavailable";
        QueueLibraryScanResult: {
            verdict: components["schemas"]["QueueLibraryScanVerdict"];
            /** Format: uuid */
            workId?: null | string;
        };
        /** @enum {unknown} */
        QueueLibraryScanVerdict: "Queued" | "Coalesced" | "NotFound";
        RecoverRequest: {
            username: null | string;
            recoveryCode: null | string;
            newPassword: null | string;
        };
        RecoverResponse: {
            verdict: components["schemas"]["RecoveryVerdict"];
        };
        RecoveryCodeResponse: {
            verdict: components["schemas"]["AccountActionVerdict"];
            recoveryCode: null | string;
            /** Format: date-time */
            expiresAt: null | string;
        };
        /** @enum {unknown} */
        RecoveryVerdict: "PasswordReplaced" | "InvalidInput" | "InvalidCode";
        RegistrationRequest: {
            username: null | string;
            password: null | string;
            email: null | string;
        };
        RegistrationRequestResponse: {
            verdict: components["schemas"]["RegistrationRequestVerdict"];
        };
        /** @enum {unknown} */
        RegistrationRequestVerdict: "Submitted" | "InvalidInput" | "InstallationUnclaimed";
        /** @enum {unknown} */
        RemediationOwner: "AutomaticRecovery" | "Administrator" | "InstallationOperator";
        SignedInAccountResponse: {
            /** Format: uuid */
            id: string;
            username: string;
            email: null | string;
            authority: components["schemas"]["AccountAuthority"];
            csrfToken: string;
        };
        SignInRequest: {
            username: null | string;
            password: null | string;
        };
        SignInResponse: {
            verdict: components["schemas"]["SignInVerdict"];
            account: null | components["schemas"]["SignedInAccountResponse"];
        };
        /** @enum {unknown} */
        SignInVerdict: "SignedIn" | "InvalidCredentials" | "ApprovalPending" | "Disabled";
        UnassessedPlaybackProfile: {
            profileKey: string;
            videoContentType: null | string;
            audioContentType: null | string;
            basicContentType: null | string;
            /** Format: int32 */
            width: null | number | string;
            /** Format: int32 */
            height: null | number | string;
            /** Format: double */
            frameRate: null | number | string;
            /** Format: int64 */
            bitrate: null | number | string;
            /** Format: int32 */
            audioChannels: null | number | string;
            /** Format: int32 */
            audioSampleRate: null | number | string;
            /** Format: int64 */
            audioBitrate: null | number | string;
        };
        /** @enum {unknown} */
        VariantSelectionReason: "PreviouslyPlayedHere" | "PositivelyAssessedAndSmooth" | "PositivelyAssessed" | "BaselineCandidate" | "NotYetAssessed" | "RuledOutHere";
        /** @enum {unknown} */
        VideoAvailability: "Available" | "Unavailable" | "Removed";
        VideoDetail: {
            video: components["schemas"]["VideoSummary"];
            /** Format: uuid */
            supersededVideoId: null | string;
        };
        /** @enum {unknown} */
        VideoFileAvailability: "Available" | "Unreachable" | "Missing" | "Replaced" | "Removed";
        /** @enum {unknown} */
        VideoFileHashState: "Pending" | "Computed" | "Incomplete" | "Failed";
        /** @enum {unknown} */
        VideoQualityBand: "Unknown" | "StandardDefinition" | "Hd720" | "FullHd1080" | "Qhd1440" | "Uhd2160" | "Uhd4320";
        VideoSummary: {
            /** Format: uuid */
            id: string;
            displayTitle: string;
            /** Format: date-time */
            discoveryDate: string;
            availability: components["schemas"]["VideoAvailability"];
            previewUrl: null | string;
            identification: components["schemas"]["IdentificationSummary"];
            playability: components["schemas"]["ClientVideoPlayability"];
            isUnsupportedVideo: boolean;
            videoFiles: components["schemas"]["PlaybackVariantView"][];
            personalState: components["schemas"]["PersonalVideoStateSummary"];
        };
        /** @enum {unknown} */
        WorkIssueAction: "RetryNow" | "CheckAgain" | "OpenPrdbSettings" | "OpenLibraryDirectory" | "ViewAffectedItems" | "CopyOperatorHandoff";
        WorkIssueActionRequest: {
            action: components["schemas"]["WorkIssueAction"];
            /** Format: int32 */
            version: number | string;
        };
        WorkIssueAffectedItem: {
            scope: string;
            containerPath: null | string;
            /** Format: uuid */
            videoFileId: null | string;
            /** Format: int32 */
            occurrenceCount: number | string;
            /** Format: date-time */
            firstOccurredAt: string;
            /** Format: date-time */
            lastOccurredAt: string;
        };
        /** @enum {unknown} */
        WorkIssueCause: "SourceAccess" | "ChangingSource" | "InvalidContent" | "Capacity" | "ExternalAvailability" | "ExternalAuthority" | "Configuration" | "InternalConsistency";
        /** @enum {unknown} */
        WorkIssueRetryDisposition: "AutomaticRetryScheduled" | "RetriesExhausted" | "NoAutomaticRetry";
        /** @enum {unknown} */
        WorkIssueSeverity: "ScopedIssue" | "OperationalBlocker" | "SafetyStop";
        WorkIssueSummary: {
            /** Format: uuid */
            id: string;
            reference: string;
            /** Format: uuid */
            backgroundWorkId: string;
            category: components["schemas"]["BackgroundWorkCategory"];
            /** Format: uuid */
            libraryDirectoryId: string;
            severity: components["schemas"]["WorkIssueSeverity"];
            cause: components["schemas"]["WorkIssueCause"];
            remediationOwner: components["schemas"]["RemediationOwner"];
            retryDisposition: components["schemas"]["WorkIssueRetryDisposition"];
            phase: string;
            summary: string;
            detail: string;
            affectedScope: string;
            containerPath: null | string;
            impact: string;
            requiredAction: string;
            expectedResolutionEvidence: string;
            /** Format: int32 */
            occurrenceCount: number | string;
            /** Format: int32 */
            affectedItemCount: number | string;
            /** Format: int32 */
            version: number | string;
            actions: components["schemas"]["WorkIssueAction"][];
            operatorHandoff: null | string;
            /** Format: uuid */
            videoId: null | string;
            /** Format: uuid */
            videoFileId: null | string;
            /** Format: date-time */
            nextAttemptAt: null | string;
            /** Format: date-time */
            firstOccurredAt: string;
            /** Format: date-time */
            lastOccurredAt: string;
            /** Format: date-time */
            resolvedAt: null | string;
            resolutionEvidence: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
