// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prdb.Viewer.Infrastructure.Persistence;

#nullable disable

namespace Prdb.Viewer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ViewerDbContext))]
    [Migration("20260827204731_AddPersonalState")]
    partial class AddPersonalState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.AccountRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.BackgroundWorkRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigurationGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CoverageComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscoveredCandidateCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FollowUpRequested")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LibraryDirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LibraryScanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingDirectoriesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category", "State", "RequestedAt");

                    b.HasIndex("LibraryDirectoryId", "Category", "ConfigurationGeneration");

                    b.ToTable("background_work", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.BootstrapAuthorizationRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("bootstrap_authorization", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.InstallationConfigurationRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivePrdbCredential")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConfiguredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstPlayableVideoReachedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastConnectionAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastConnectionIssue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastConnectionVerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PendingCredentialRevision")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingPrdbCredential")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrdbConnectionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("installation_configuration", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrdbConnectionStatus = "Missing"
                        });
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.LibraryDirectoryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigurationGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InitialProcessingStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerPath")
                        .IsUnique()
                        .HasFilter("\"State\" = 'Active'");

                    b.HasIndex("State");

                    b.ToTable("library_directory", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.LibraryDirectoryStageRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("library_directory_stage", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PersonalVideoStateRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AccumulatedWatchDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ContinueWatchingDismissedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FavouriteAddedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasViewingCompletion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastQualifiedActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonalRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlayStateChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PlaybackProgressMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProgressVideoFileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WatchLaterAddedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId", "VideoId");

                    b.HasIndex("VideoId");

                    b.HasIndex("AccountId", "FavouriteAddedAt");

                    b.HasIndex("AccountId", "LastQualifiedActivityAt");

                    b.HasIndex("AccountId", "WatchLaterAddedAt");

                    b.ToTable("personal_video_state", null, t =>
                        {
                            t.HasCheckConstraint("CK_personal_video_state_PersonalRating", "\"PersonalRating\" IS NULL OR \"PersonalRating\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PlaybackAttemptRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ActiveWatchDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CompletionRecorded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastPositionMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastReportSequence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Qualified")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ViewingSessionBeganAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("AccountId", "EndedAt", "LastActivityAt");

                    b.HasIndex("AccountId", "VideoId", "AttemptedAt");

                    b.ToTable("playback_attempt", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PlaybackAttemptVideoFileRow", b =>
                {
                    b.Property<Guid>("PlaybackAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoFileId")
                        .HasColumnType("TEXT");

                    b.HasKey("PlaybackAttemptId", "VideoFileId");

                    b.HasIndex("VideoFileId");

                    b.ToTable("playback_attempt_video_file", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PlaybackReportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("ActiveWatchingMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActivityEndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActivityStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlaybackAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PositionMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityStartedAt", "ActivityEndedAt");

                    b.HasIndex("PlaybackAttemptId", "Sequence");

                    b.ToTable("playback_report", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.RecoveryCodeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("recovery_code", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CsrfTokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoFileCandidateRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LibraryDirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryScanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedLastWriteTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryScanId", "RelativePath")
                        .IsUnique();

                    b.HasIndex("LibraryScanId", "State");

                    b.ToTable("video_file_candidate", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoFileRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioCodec")
                        .HasColumnType("TEXT");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveCompleteAbsences")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectPlayClassification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InspectedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LastObservedScanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWriteTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryDirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicDeliveryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoCodec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicDeliveryId")
                        .IsUnique();

                    b.HasIndex("VideoId");

                    b.HasIndex("LibraryDirectoryId", "RelativePath");

                    b.HasIndex("LibraryDirectoryId", "Sha256");

                    b.ToTable("video_file", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveryDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryDate");

                    b.ToTable("video", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.WorkIssueRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedScope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BackgroundWorkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemediationOwner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundWorkId", "ResolvedAt");

                    b.ToTable("work_issue", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.BackgroundWorkRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.LibraryDirectoryRow", "LibraryDirectory")
                        .WithMany()
                        .HasForeignKey("LibraryDirectoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LibraryDirectory");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PersonalVideoStateRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.AccountRow", "Account")
                        .WithMany("PersonalVideoStates")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.VideoRow", "Video")
                        .WithMany("PersonalStates")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PlaybackAttemptRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.AccountRow", "Account")
                        .WithMany("PlaybackAttempts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.VideoRow", "Video")
                        .WithMany("PlaybackAttempts")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PlaybackAttemptVideoFileRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.PlaybackAttemptRow", "PlaybackAttempt")
                        .WithMany("VideoFiles")
                        .HasForeignKey("PlaybackAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.VideoFileRow", "VideoFile")
                        .WithMany("PlaybackAttempts")
                        .HasForeignKey("VideoFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlaybackAttempt");

                    b.Navigation("VideoFile");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PlaybackReportRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.PlaybackAttemptRow", "PlaybackAttempt")
                        .WithMany("Reports")
                        .HasForeignKey("PlaybackAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaybackAttempt");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.RecoveryCodeRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.AccountRow", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.AccountRow", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoFileRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.LibraryDirectoryRow", "LibraryDirectory")
                        .WithMany()
                        .HasForeignKey("LibraryDirectoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.VideoRow", "Video")
                        .WithMany("VideoFiles")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LibraryDirectory");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.WorkIssueRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.BackgroundWorkRow", "BackgroundWork")
                        .WithMany()
                        .HasForeignKey("BackgroundWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackgroundWork");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.AccountRow", b =>
                {
                    b.Navigation("PersonalVideoStates");

                    b.Navigation("PlaybackAttempts");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PlaybackAttemptRow", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("VideoFiles");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoFileRow", b =>
                {
                    b.Navigation("PlaybackAttempts");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoRow", b =>
                {
                    b.Navigation("PersonalStates");

                    b.Navigation("PlaybackAttempts");

                    b.Navigation("VideoFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
