// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prdb.Viewer.Infrastructure.Persistence;

#nullable disable

namespace Prdb.Viewer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ViewerDbContext))]
    [Migration("20260827192517_AddInstallationConfiguration")]
    partial class AddInstallationConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.AccountRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.BootstrapAuthorizationRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("bootstrap_authorization", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.InstallationConfigurationRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivePrdbCredential")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConfiguredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastConnectionAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastConnectionIssue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastConnectionVerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PendingCredentialRevision")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingPrdbCredential")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrdbConnectionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("installation_configuration", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrdbConnectionStatus = "Missing"
                        });
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.LibraryDirectoryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigurationGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InitialProcessingStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerPath")
                        .IsUnique()
                        .HasFilter("\"State\" = 'Active'");

                    b.HasIndex("State");

                    b.ToTable("library_directory", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.LibraryDirectoryStageRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("library_directory_stage", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.RecoveryCodeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("recovery_code", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CsrfTokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.RecoveryCodeRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.AccountRow", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.AccountRow", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
