// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prdb.Viewer.Infrastructure.Persistence;

#nullable disable

namespace Prdb.Viewer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ViewerDbContext))]
    [Migration("20260829134638_DeriveCsrfTokenFromSession")]
    partial class DeriveCsrfTokenFromSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.AccountRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludesNotReadyForDirectPlay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.BackgroundWorkRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigurationGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CoverageComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscoveredCandidateCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FollowUpRequested")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryDirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LibraryScanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingDirectoriesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateBeforePause")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WaitingReason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category", "State", "RequestedAt");

                    b.HasIndex("LibraryDirectoryId", "Category", "ConfigurationGeneration");

                    b.ToTable("background_work", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.BootstrapAuthorizationRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("bootstrap_authorization", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.ClientPlaybackAssessmentRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientContextKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PowerEfficient")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Smooth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId", "ClientContextKey", "ProfileKey");

                    b.ToTable("client_playback_assessment", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.IdentificationCandidateRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DecidedByAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PriorRejectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupportingVideoFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "EvidenceClass", "CreatedAt");

                    b.HasIndex("VideoId", "Dimension", "Status");

                    b.HasIndex("VideoId", "Dimension", "TargetKey", "EvidenceKey");

                    b.ToTable("identification_candidate", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.IdentificationClaimRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DecidedByAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EstablishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdministrativeOverride")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupportingVideoFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Dimension", "TargetKey", "Status");

                    b.HasIndex("VideoId", "Dimension", "Status");

                    b.ToTable("identification_claim", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.IdentificationDecisionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CandidateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DecidedByAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MergedAnotherVideo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriorState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultingState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKey")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VideoId", "CreatedAt");

                    b.ToTable("identification_decision", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.InstallationConfigurationRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivePrdbCredential")
                        .HasColumnType("TEXT");

                    b.Property<bool>("BackgroundWorkPaused")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BackgroundWorkPausedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConfiguredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstPlayableVideoReachedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastConnectionAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastConnectionIssue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastConnectionVerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PendingCredentialRevision")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingPrdbCredential")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrdbConnectionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SiteDirectoryFetchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("installation_configuration", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundWorkPaused = false,
                            PrdbConnectionStatus = "Missing"
                        });
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.LibraryDirectoryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigurationGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InitialProcessingStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerPath")
                        .IsUnique()
                        .HasFilter("\"State\" = 'Active'");

                    b.HasIndex("State");

                    b.ToTable("library_directory", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.LibraryDirectoryStageRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("library_directory_stage", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.ObservedPlaybackOutcomeRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientContextKey")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCategory")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId", "ClientContextKey", "VideoFileId");

                    b.HasIndex("VideoFileId");

                    b.ToTable("observed_playback_outcome", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PersonalVideoStateRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AccumulatedWatchDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ContinueWatchingDismissedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FavouriteAddedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasViewingCompletion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastQualifiedActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonalRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlayStateChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PlaybackProgressMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProgressVideoFileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WatchLaterAddedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId", "VideoId");

                    b.HasIndex("VideoId");

                    b.HasIndex("AccountId", "FavouriteAddedAt");

                    b.HasIndex("AccountId", "LastQualifiedActivityAt");

                    b.HasIndex("AccountId", "WatchLaterAddedAt");

                    b.ToTable("personal_video_state", null, t =>
                        {
                            t.HasCheckConstraint("CK_personal_video_state_PersonalRating", "\"PersonalRating\" IS NULL OR \"PersonalRating\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PlaybackAttemptRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ActiveWatchDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CompletionRecorded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastPositionMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastReportSequence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Qualified")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ViewingSessionBeganAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("AccountId", "EndedAt", "LastActivityAt");

                    b.HasIndex("AccountId", "VideoId", "AttemptedAt");

                    b.ToTable("playback_attempt", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PlaybackAttemptVideoFileRow", b =>
                {
                    b.Property<Guid>("PlaybackAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoFileId")
                        .HasColumnType("TEXT");

                    b.HasKey("PlaybackAttemptId", "VideoFileId");

                    b.HasIndex("VideoFileId");

                    b.ToTable("playback_attempt_video_file", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PlaybackReportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("ActiveWatchingMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActivityEndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActivityStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlaybackAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PositionMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityStartedAt", "ActivityEndedAt");

                    b.HasIndex("PlaybackAttemptId", "Sequence");

                    b.ToTable("playback_report", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.RecoveryCodeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("recovery_code", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.SiteDirectoryEntryRow", b =>
                {
                    b.Property<string>("SiteKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("SiteKey");

                    b.ToTable("site_directory_entry", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoActorRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("VideoId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("video_actor", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoFileCandidateRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LibraryDirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryScanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedLastWriteTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryScanId", "RelativePath")
                        .IsUnique();

                    b.HasIndex("LibraryScanId", "State");

                    b.ToTable("video_file_candidate", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoFileRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AudioBitrate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AudioChannels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioCodec")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AudioSampleRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveCompleteAbsences")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectPlayClassification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FrameRate")
                        .HasColumnType("REAL");

                    b.Property<string>("HashFailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HashedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedSha256")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("IdentifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifiedSha256")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InspectedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LastObservedScanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWriteTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryDirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerceptualHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PreviewGeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewSha256")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreviousVideoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicDeliveryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PublicPreviewId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SiteRecognisedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteRecognisedPath")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("VideoBitrate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoCodec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VideoLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoProfile")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileKey");

                    b.HasIndex("PublicDeliveryId")
                        .IsUnique();

                    b.HasIndex("PublicPreviewId")
                        .IsUnique();

                    b.HasIndex("LibraryDirectoryId", "RelativePath");

                    b.HasIndex("LibraryDirectoryId", "Sha256");

                    b.HasIndex("LibraryDirectoryId", "Availability", "HashState");

                    b.HasIndex("LibraryDirectoryId", "Availability", "PreviewState");

                    b.HasIndex("LibraryDirectoryId", "Availability", "SiteRecognisedPath");

                    b.HasIndex("VideoId", "Availability", "DirectPlayClassification", "ProfileKey");

                    b.ToTable("video_file", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoMetadataRow", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtworkUrl")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrdbVideoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VideoId");

                    b.HasIndex("PrdbVideoId");

                    b.ToTable("video_metadata", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BestClassification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CaseVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DiscoveryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EstablishedSite")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasEstablishedWork")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProjectedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReviewNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SurvivingVideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryDate");

                    b.HasIndex("ProjectedAt");

                    b.HasIndex("SurvivingVideoId");

                    b.HasIndex("SurvivingVideoId", "Availability", "BestClassification", "DiscoveryDate");

                    b.HasIndex("SurvivingVideoId", "Availability", "BestClassification", "DisplayLabel");

                    b.ToTable("video", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.WorkIssueItemRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstOccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VideoFileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkIssueId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkIssueId", "Scope")
                        .IsUnique();

                    b.ToTable("work_issue_item", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.WorkIssueRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AffectedItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AffectedScope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregationKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptedRetries")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BackgroundWorkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigurationGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedResolutionEvidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstOccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryDirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreviousOccurrenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemediationOwner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionEvidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetryDisposition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SafeCause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("VideoFileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("AggregationKey", "ResolvedAt");

                    b.HasIndex("BackgroundWorkId", "ResolvedAt");

                    b.HasIndex("ResolvedAt", "Severity", "LastOccurredAt");

                    b.ToTable("work_issue", (string)null);
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.BackgroundWorkRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.LibraryDirectoryRow", "LibraryDirectory")
                        .WithMany()
                        .HasForeignKey("LibraryDirectoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LibraryDirectory");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.ClientPlaybackAssessmentRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.AccountRow", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.IdentificationCandidateRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.VideoRow", "Video")
                        .WithMany("IdentificationCandidates")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.IdentificationClaimRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.VideoRow", "Video")
                        .WithMany("IdentificationClaims")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.ObservedPlaybackOutcomeRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.AccountRow", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.VideoFileRow", "VideoFile")
                        .WithMany()
                        .HasForeignKey("VideoFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("VideoFile");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PersonalVideoStateRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.AccountRow", "Account")
                        .WithMany("PersonalVideoStates")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.VideoRow", "Video")
                        .WithMany("PersonalStates")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PlaybackAttemptRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.AccountRow", "Account")
                        .WithMany("PlaybackAttempts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.VideoRow", "Video")
                        .WithMany("PlaybackAttempts")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PlaybackAttemptVideoFileRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.PlaybackAttemptRow", "PlaybackAttempt")
                        .WithMany("VideoFiles")
                        .HasForeignKey("PlaybackAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.VideoFileRow", "VideoFile")
                        .WithMany("PlaybackAttempts")
                        .HasForeignKey("VideoFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlaybackAttempt");

                    b.Navigation("VideoFile");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PlaybackReportRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.PlaybackAttemptRow", "PlaybackAttempt")
                        .WithMany("Reports")
                        .HasForeignKey("PlaybackAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaybackAttempt");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.RecoveryCodeRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.AccountRow", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.AccountRow", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoActorRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.VideoRow", "Video")
                        .WithMany("ProjectedActors")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoFileRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.LibraryDirectoryRow", "LibraryDirectory")
                        .WithMany()
                        .HasForeignKey("LibraryDirectoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.VideoRow", "Video")
                        .WithMany("VideoFiles")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LibraryDirectory");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoMetadataRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.VideoRow", "Video")
                        .WithOne("Metadata")
                        .HasForeignKey("Prdb.Viewer.Infrastructure.Persistence.VideoMetadataRow", "VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.WorkIssueItemRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.WorkIssueRow", "WorkIssue")
                        .WithMany()
                        .HasForeignKey("WorkIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkIssue");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.WorkIssueRow", b =>
                {
                    b.HasOne("Prdb.Viewer.Infrastructure.Persistence.BackgroundWorkRow", "BackgroundWork")
                        .WithMany()
                        .HasForeignKey("BackgroundWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackgroundWork");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.AccountRow", b =>
                {
                    b.Navigation("PersonalVideoStates");

                    b.Navigation("PlaybackAttempts");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.PlaybackAttemptRow", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("VideoFiles");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoFileRow", b =>
                {
                    b.Navigation("PlaybackAttempts");
                });

            modelBuilder.Entity("Prdb.Viewer.Infrastructure.Persistence.VideoRow", b =>
                {
                    b.Navigation("IdentificationCandidates");

                    b.Navigation("IdentificationClaims");

                    b.Navigation("Metadata");

                    b.Navigation("PersonalStates");

                    b.Navigation("PlaybackAttempts");

                    b.Navigation("ProjectedActors");

                    b.Navigation("VideoFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
